package com.zer0rez.euler.problems

import com.zer0rez.euler.Problem
import com.zer0rez.euler.Solution
import com.zer0rez.euler.util.Util

/**
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
Answer: 4613732
 */
// https://projecteuler.net/problem=2
class Problem2 : Problem {
    override fun solve(): Solution {
        val filtered = Util.fibonacci { it > 4000000 }.filter { it % 2 == 0 }
        return Solution(2, filtered.sum().toString(), "${filtered.joinToString(", ")}")
    }
}